# Generated by Django 4.0.1 on 2022-01-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('memory', 'memory'), ('travel', 'travel'), ('vacation', 'vacation'), ('home', 'home')], default='memory', max_length=8),
        ),
    ]
